language: node_js
node_js: 0.12.2
before_install:
- npm install -g grunt-cli
- gem install sass
install:
- npm install
script:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then grunt
  publish; else grunt build; fi
branches:
  only:
  - master
env:
  global:
    TRAVIS_REPO_SLUG=stmeissner/commercetools-sunrise-design
